/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;

/**
 *
 * @author cesar
 */
public class formPokemon extends javax.swing.JFrame {

    /**
     * Creates new form formPokemon
     */
    public formPokemon() {
        initComponents();
        this.setSize(1033, 467);
        
        this.setSize(new Dimension(1033, 467));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtExpPok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarPok = new javax.swing.JTextField();
        txtNombrePok = new javax.swing.JTextField();
        txtPesoPok = new javax.swing.JTextField();
        txtAlturaPok = new javax.swing.JTextField();
        panelImagen = new javax.swing.JPanel();
        labelImagenPok = new javax.swing.JLabel();
        buttonBuscarPok = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePokemon = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Experiencia base:");
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 130, -1));

        txtExpPok.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        panelMenu.add(txtExpPok, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 70, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        panelMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Peso:");
        panelMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Altura:");
        panelMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, -1));

        txtBuscarPok.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtBuscarPok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPokActionPerformed(evt);
            }
        });
        panelMenu.add(txtBuscarPok, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 30));

        txtNombrePok.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtNombrePok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePokActionPerformed(evt);
            }
        });
        panelMenu.add(txtNombrePok, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 70, 30));

        txtPesoPok.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        panelMenu.add(txtPesoPok, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 70, 30));

        txtAlturaPok.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        panelMenu.add(txtAlturaPok, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 70, 30));

        panelImagen.setBackground(new java.awt.Color(204, 204, 255));

        labelImagenPok.setText("jLabel2");

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelImagenPok, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelImagenPok, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        panelMenu.add(panelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 190, 220));

        buttonBuscarPok.setText("Buscar");
        buttonBuscarPok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarPokActionPerformed(evt);
            }
        });
        panelMenu.add(buttonBuscarPok, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 90, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("Buscador de pokemones");
        panelMenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, -1));

        panelPrincipal.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 470, 380));

        tablePokemon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePokemon);

        panelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 480, 380));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Descripcion de los pokemones");
        panelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 350, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelPrincipal.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePokActionPerformed

    private void txtBuscarPokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPokActionPerformed

    private void buttonBuscarPokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarPokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarPokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscarPok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImagenPok;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablePokemon;
    private javax.swing.JTextField txtAlturaPok;
    private javax.swing.JTextField txtBuscarPok;
    private javax.swing.JTextField txtExpPok;
    private javax.swing.JTextField txtNombrePok;
    private javax.swing.JTextField txtPesoPok;
    // End of variables declaration//GEN-END:variables
}
